import { Inter } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import TopBar from "./components/TopBar/TopBar";
import Footer from "./components/Footer/Footer";
config.autoAddCss = false;

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const playFairFont = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Woodys Famous Greek Salads",
  description: "Generated by create next app",
  themeColor: "#ecd96f",
};
{/* <meta name="theme-color" content="#ecd96f"> */}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${playFairFont.className}`}>
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
